import animation from './includes/animation.js';
import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import scrollToId from './includes/scrollToId.js';
import modal from './includes/modal.js';
import langDropdown from './includes/langDropdown.js';
import actionsDropdown from './includes/actionsDropdown.js';
import isDropdown from './includes/isDropdown.js';
import validation from './includes/validation.js';
import closeAlert from './includes/closeAlert.js';
import projectsSlider from './includes/projectsSlider.js';
import loadMore from './includes/loadMore.js';
import productsSlider from './includes/productsSlider.js';
import photoSwipe from './includes/photoSwipe.js';
import '../sass/main.sass';


fixHeight();
animation();
mobileNav();
scrollToId();
modal();
langDropdown();
actionsDropdown();
isDropdown();
validation();
closeAlert();
projectsSlider();
loadMore();
productsSlider();
photoSwipe();